### ISSUE TITLE
Does not run in Windows Server 2008 R2

### ISSUE THREAD

**Issue by acastiello** [mk-fg/acme-cert-tool#2]
Python 3.8.0 installed. Just creating an account key shows error:

D:\acme-cert-tool>acme-cert-tool.py  -gk "account_key.pem"
Traceback (most recent call last):
  File "acme-cert-tool.py", line 1038, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "acme-cert-tool.py", line 886, in main
    acc_key = AccKey.generate_to_file(p_acc_key, opts.key_type, file_mode=file_m
ode)
  File "acme-cert-tool.py", line 197, in generate_to_file
    with safe_replacement( p_acc_key,
  File "c:\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "acme-cert-tool.py", line 47, in safe_replacement
    if mode is not None: os.fchmod(tmp.fileno(), mode)
AttributeError: module 'os' has no attribute 'fchmod'

a empty file named "account_key.pem.bq_j1mqk" is created (different name on each run)

Does the tool only run on Linux? "fchmod" sounds like that

**Comment by mk-fg** [comment]
> Does the tool only run on Linux? "fchmod" sounds like that

Yes, unfortunately, almost certainly shouldn't work there.
It might work on Windows 10 with WSL/WSL2, but I've never tested it there, so might need some compatibility tweaks even with that compatibility layer.

Don't use Windows myself, and don't really know what are the differences between platforms to do any kind of port, and not sure if it's even relevant in that ecosystem in any way.
(IIS and such probably have their own mechanisms and/or APIs for dealing with ACME certs)

Guess I should probably mention it in the README, will update it.
Thanks for reporting!
